spring:
  liquibase:
    url: jdbc:postgresql://postgres-user:5431/user-service
  datasource:
    url: jdbc:postgresql://postgres-user:5431/user-service
keycloak:
  auth-server-url: http://keycloak:8080
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
