keycloak:
  auth-server-url: http://localhost:8080
  realm: sem4Infras
  cors: 'true'
  cors-max-age: '0'
  bearer-only: 'true'
  ssl-required: external
  resource: login-app
  principal-attribute: preferred_username
  public-client: 'true'
  use-resource-role-mappings: 'true'
spring:
  main:
    allow-bean-definition-overriding: 'true'
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    password: admin
    user: admin
    url: jdbc:postgresql://localhost:5431/user-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5431/user-service
  config:
    import: roles.properties
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/sem4Infras/protocol/openid-connect/certs
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security=DEBUG:
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
admin:
  keycloak:
    client-secret: 'M18XOUsxN52C14ZGZs2OpHygjnCZJIFe'
    client-id: backend-client
    group-customerId: 'd741ea9d-e85f-4e0a-a934-993d12a10c46'
    group-employeeId: '81d699a2-7878-48b9-8336-1a62419ff469'
